### ISSUE TITLE
Cannot open provider settings when provider is disabled

### ISSUE THREAD

**Issue by rhenwinch** [rhenwinch/Flixclusive#104]
### Steps to reproduce

1. Disable a provider, say _Stremio_
2. Restart app
3. Open provider settings of _Stremio_

### Expected behavior

Should open

### Actual behavior

Crashes

### Crash logs (or stack trace)

java.lang.reflect.InvocationTargetExceptionat java.lang.reflect.Method.invoke(Native Method)
at com.flixclusive.feature.mobile.provider.settings.ProviderSettingsScreenKt.ProviderSettingsScreen(ProviderSettingsScreen.kt:50)
at com.flixclusive.feature.mobile.provider.settings.destinations.ProviderSettingsScreenDestination.Content(ProviderSettingsScreenDestination.kt:58)

### Flixclusive version

pre-release

### Android version

SDK 29

### Device

emulator

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Nvm, this only happens on Stremio.
