### ISSUE TITLE
Updater throwing an error

### ISSUE THREAD

**Issue by oathzed** [rhenwinch/Flixclusive#24]
Device: Google pixel 7
Sdk: 34
App version: 1.3.1

java.lang.RuntimeException: Unable to create service com.flixclusive.service.app_updater.AppUpdaterService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{f797924 23187:com.flixclusive/u0a291} targetSDK=34
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{f797924 23187:com.flixclusive/u0a291} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at com.flixclusive.service.app_updater.AppUpdaterService.onCreate(SourceFile:101)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
	... 9 more

**Comment by rhenwinch** [comment]
SDK 34 issue. will look into this

**Comment by rhenwinch** [comment]
for now i advice to manually install the app. i havent migrated most of the code for SDK 34 since I started this one with 34 being current beta version back in July. totally my fault

**Comment by oathzed** [comment]
> for now i advice to manually install the app. i havent migrated most of the code for SDK 34 since I started this one with 34 being current beta version back in July. totally my fault

Copy that. Sounds good man, no worries
