### ISSUE TITLE
Error, no posters showing

### ISSUE THREAD

**Issue by oathzed** [rhenwinch/Flixclusive#25]
Hey, I've been playing with the app and some times when I e been opening it, it just tries to load the posters but nothing shows up. Not sure if TMDB is having issues or what.

But I also got this error after (p.s let me know if you automatically get sent these, so I don't keep annoying u with bug reports lol.)

Device: pixel 7
Sdk 34
V1.3.1

java.lang.NullPointerException
	at o.p.a(SourceFile:75)
	at o.p.p(SourceFile:46)
	at s0.c.e(SourceFile:46)
	at s0.c.p(SourceFile:1)
	at x.i.U(SourceFile:128)
	at s0.c.d(SourceFile:46)
	at s0.c.U(SourceFile:1)
	at p.m0.a(SourceFile:481)
	at p.m0.q(SourceFile:174)
	at s0.c.q(SourceFile:54)
	at kg.j.B(SourceFile:180)
	at id.a.I(SourceFile:183)
	at x.n.e(SourceFile:35)
	at x.m.a(SourceFile:99)
	at x.m.q(SourceFile:65)
	at s0.c.q(SourceFile:54)
	at kg.j.B(SourceFile:180)
	at t0.g.e(SourceFile:98)
	at z.p0.e(SourceFile:23)
	at id.a.t0(SourceFile:113)
	at u.d0.b(SourceFile:1004)
	at u.d0.q(SourceFile:407)
	at s0.c.q(SourceFile:54)
	at u.d0.b(SourceFile:626)
	at u.d0.q(SourceFile:259)
	at s0.c.q(SourceFile:54)
	at uc.e.J0(SourceFile:1)
	at k0.o.r(SourceFile:130)
	at k0.t.o(SourceFile:29)
	at k0.c2.a(SourceFile:42)
	at k0.l.a(SourceFile:5)
	at k0.l.a(SourceFile:5)
	at o1.f0.i(SourceFile:46)
	at o1.f0.h(SourceFile:104)
	at o1.a0.t(SourceFile:174)
	at z.y.a(SourceFile:1)
	at x.t.a(SourceFile:19)
	at x.u.q(SourceFile:712)
	at u.d0.q(SourceFile:388)
	at o1.c0.e(SourceFile:74)
	at q1.p.a(SourceFile:51)
	at t.m.f(SourceFile:44)
	at t.m.p(SourceFile:650)
	at o1.x.h(SourceFile:8)
	at q1.p.a(SourceFile:83)
	at t.m.f(SourceFile:10)
	at t.m.p(SourceFile:667)
	at o1.x.h(SourceFile:8)
	at q1.p.a(SourceFile:83)
	at b1.q0.h(SourceFile:1)
	at q1.p.a(SourceFile:83)
	at q1.e0.a(SourceFile:24)
	at q1.e0.invoke(SourceFile:9)
	at rh.e0.z(SourceFile:59)
	at u0.y.a(SourceFile:48)
	at u0.z.c(SourceFile:162)
	at q1.j1.a(SourceFile:1)
	at q1.f0.u0(SourceFile:139)
	at q1.f0.a(SourceFile:119)
	at w.t.e(SourceFile:214)
	at q1.p.a(SourceFile:51)
	at w.e0.h(SourceFile:99)
	at q1.p.a(SourceFile:83)
	at q1.e0.a(SourceFile:24)
	at q1.e0.invoke(SourceFile:9)
	at rh.e0.z(SourceFile:59)
	at u0.y.a(SourceFile:48)
	at u0.z.c(SourceFile:162)
	at q1.j1.a(SourceFile:1)
	at q1.f0.u0(SourceFile:139)
	at q1.m0.c(SourceFile:44)
	at q1.m0.k(SourceFile:140)
	at q1.m0.h(SourceFile:67)
	at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:32)
	at q1.f1.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:23892)
	at android.view.View.updateDisplayListIfDirty(View.java:22756)
	at android.view.View.draw(View.java:23620)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
	at android.view.View.updateDisplayListIfDirty(View.java:22747)
	at android.view.View.draw(View.java:23620)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
	at android.view.View.updateDisplayListIfDirty(View.java:22747)
	at android.view.View.draw(View.java:23620)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
	at android.view.View.updateDisplayListIfDirty(View.java:22747)
	at android.view.View.draw(View.java:23620)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
	at android.view.View.draw(View.java:23892)
	at com.android.internal.policy.DecorView.draw(DecorView.java:809)
	at android.view.View.updateDisplayListIfDirty(View.java:22756)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by rhenwinch** [comment]
> so I don't keep annoying u with bug reports lol
all good bro. I dont have any backend loggers for exceptions so these dont get sent to mine. but will add an **optional button** to automatically send it to my end.

**Comment by oathzed** [comment]
> > so I don't keep annoying u with bug reports lol
> 
> all good bro. I dont have any backend loggers for exceptions so these dont get sent to mine. but will add an **optional button** to automatically send it to my end.

Ok great, thank u

**Comment by rhenwinch** [comment]
> it just tries to load the posters but nothing shows up

does this often happen?

**Comment by oathzed** [comment]
> > it just tries to load the posters but nothing shows up
> 
> does this often happen?

It was happening alot that night but not recently

**Comment by rhenwinch** [comment]
It must be the ImageLoader from Coil:

https://github.com/rhenwinch/Flixclusive/blob/a90215b8c40ac0675cd217b38b842d2d57c90acc/app/src/main/java/com/flixclusive/FlixclusiveApplication.kt#L28-L32

**Comment by oathzed** [comment]
Ahh got yehh
