### ISSUE TITLE
Problem ok my device 

### ISSUE THREAD

**Issue by Hamrfulanture** [rhenwinch/Flixclusive#34]
java.lang.NullPointerException
	at o.p.a(SourceFile:75)
	at o.p.p(SourceFile:46)
	at s0.c.e(SourceFile:46)
	at s0.c.p(SourceFile:1)
	at x.i.U(SourceFile:128)
	at s0.c.d(SourceFile:46)
	at s0.c.U(SourceFile:1)
	at p.m0.a(SourceFile:481)
	at p.m0.q(SourceFile:174)
	at s0.c.q(SourceFile:54)
	at kg.j.B(SourceFile:180)
	at id.a.I(SourceFile:183)
	at x.n.e(SourceFile:35)
	at x.m.a(SourceFile:99)
	at x.m.q(SourceFile:65)
	at s0.c.q(SourceFile:54)
	at kg.j.B(SourceFile:180)
	at t0.g.e(SourceFile:98)
	at z.p0.e(SourceFile:23)
	at id.a.t0(SourceFile:113)
	at u.d0.b(SourceFile:1004)
	at u.d0.q(SourceFile:406)
	at s0.c.q(SourceFile:54)
	at u.d0.b(SourceFile:626)
	at u.d0.q(SourceFile:258)
	at s0.c.q(SourceFile:54)
	at uc.e.J0(SourceFile:1)
	at k0.o.r(SourceFile:130)
	at k0.t.o(SourceFile:29)
	at k0.c2.a(SourceFile:42)
	at k0.l.a(SourceFile:5)
	at k0.l.a(SourceFile:5)
	at o1.f0.i(SourceFile:46)
	at o1.f0.h(SourceFile:104)
	at o1.a0.t(SourceFile:174)
	at z.y.a(SourceFile:1)
	at x.t.a(SourceFile:19)
	at x.u.q(SourceFile:712)
	at u.d0.q(SourceFile:387)
	at o1.c0.e(SourceFile:74)
	at q1.p.a(SourceFile:51)
	at b1.q0.h(SourceFile:1)
	at q1.p.a(SourceFile:83)
	at q1.e0.a(SourceFile:24)
	at q1.e0.invoke(SourceFile:9)
	at rh.e0.z(SourceFile:59)
	at u0.y.a(SourceFile:48)
	at u0.z.c(SourceFile:162)
	at q1.j1.a(SourceFile:1)
	at q1.f0.u0(SourceFile:139)
	at q1.f0.a(SourceFile:119)
	at w.t.e(SourceFile:214)
	at q1.p.a(SourceFile:51)
	at w.e0.h(SourceFile:99)
	at q1.p.a(SourceFile:83)
	at q1.e0.a(SourceFile:24)
	at q1.e0.invoke(SourceFile:9)
	at rh.e0.z(SourceFile:59)
	at u0.y.a(SourceFile:48)
	at u0.z.c(SourceFile:162)
	at q1.j1.a(SourceFile:1)
	at q1.f0.u0(SourceFile:139)
	at q1.m0.c(SourceFile:44)
	at q1.m0.k(SourceFile:140)
	at q1.m0.h(SourceFile:67)
	at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:32)
	at q1.f1.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:22508)
	at android.view.View.updateDisplayListIfDirty(View.java:21367)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
	at android.view.View.updateDisplayListIfDirty(View.java:21325)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
	at android.view.View.updateDisplayListIfDirty(View.java:21325)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
	at android.view.View.updateDisplayListIfDirty(View.java:21325)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
	at android.view.View.updateDisplayListIfDirty(View.java:21325)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4273)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3978)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3239)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2065)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8495)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:826)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by rhenwinch** [comment]
Home content bug. gonna get fixed soon !!
