### ISSUE TITLE
Failed to build. EDIT: AdMob support

### ISSUE THREAD

**Issue by Tvmax46** [rhenwinch/Flixclusive#40]
a problem was found with the configuration of task 'app:kaptDebugkotlin' (type 'KspTaskjvm')

**Comment by rhenwinch** [comment]
could u paste the stacktrace?

**Comment by Tvmax46** [comment]
i am not good in coding i just tried to install in android studio but i get error when building app/gradle...the developer i hired on fiverr also got the same error

**Comment by Tvmax46** [comment]
![Screenshot 2023-12-25 143720](https://github.com/rhenwinch/Flixclusive/assets/154805624/98fa27d8-2780-46c3-9687-d002940c4ffb)
here..

**Comment by Tvmax46** [comment]
java.lang.RuntimeException: Cannot find service com.android.tools.idea.explainer.IssueExplainer (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Android, id=org.jetbrains.android, descriptorPath=plugin.xml, path=C:\Program Files\Android\Android Studio\plugins\android, version=231.9392.1.2311.11076708, package=null, isBundled=true), packagePrefix=null, instanceId=111, state=active), client=null)
	at com.android.tools.idea.gradle.actions.ExplainSyncOrBuildOutput.<init>(ExplainSyncOrBuildOutput.kt:71)
	at com.android.tools.idea.gradle.project.build.invoker.GradleBuildInvokerImpl$MyListener$onStart$buildDescriptor$1.apply(GradleBuildInvokerImpl.kt:431)
	at com.android.tools.idea.gradle.project.build.invoker.GradleBuildInvokerImpl$MyListener$onStart$buildDescriptor$1.apply(GradleBuildInvokerImpl.kt:429)
	at com.intellij.build.DefaultBuildDescriptor.lambda$getContextActions$0(DefaultBuildDescriptor.java:147)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1951)
	at com.intellij.build.DefaultBuildDescriptor.getContextActions(DefaultBuildDescriptor.java:147)
	at com.intellij.build.BuildTreeConsoleView$1.invokePopup(BuildTreeConsoleView.java:228)
	at com.intellij.ui.PopupHandler.mouseReleased(PopupHandler.java:55)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:424)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by rhenwinch** [comment]
seems like app/schemas folder isnt getting created.

Try creating a folder named `schemas` inside the app folder.

![image](https://github.com/rhenwinch/Flixclusive/assets/52451354/f4f8e6a6-ae0c-4815-8662-cca2a2be00ba)

**Comment by rhenwinch** [comment]
seems like the schemas folder wasnt shipped with the files. this is an easy fix but still busy sorry

**Comment by Tvmax46** [comment]
thanks,,, solved, nice work

**Comment by Tvmax46** [comment]
![Screenshot 2023-12-25 185451](https://github.com/rhenwinch/Flixclusive/assets/154805624/b1681bca-9800-436f-87c0-bdbb0176c537)
this

**Comment by rhenwinch** [comment]
What java version do u have in your android studio?

**Comment by Tvmax46** [comment]
jdk 11.0.16.1 if i am not wrong

**Comment by Tvmax46** [comment]
jdk 18 solved it

**Comment by Tvmax46** [comment]
Can you do customization for payment.. like adding admob and join telegram link?

**Comment by rhenwinch** [comment]
Sorry man. Not interested in adding ads on the app if that's what you're asking.

**Comment by oathzed** [comment]
> Sorry man. Not interested in adding ads on the app if that's what you're asking.

I think he's trying to rebrand your app and sell it lmao.

Merry Christmas man! Take a break you deserve it :)

**Comment by Tvmax46** [comment]
@oathzed stop being stupid, asking for ads is just the same customization request like  those who are asking for more video sources or trailer player.
If i ask for tailer player, does that mean i want to sell the app?.
Sell it to who? to your mother?.
Again i was directing my request to the developer and not you.

**Comment by oathzed** [comment]
> @oathzed stop being stupid, asking for ads is just the same customization request like those who are asking for more video sources or trailer player. If i ask for trailer player, does that mean i want to sell the app?. Sell it to who? to your mother?. Again i was directing my request to the developer and not you.

Yeh sure bud.

**Comment by Monicamonicah** [comment]
rhe

> Sorry man. Not interested in adding ads on the app if that's what you're asking.

First your project is really nice, we all appreaciate..
To be honest i really wish you could implement admob or some documentation on how to do it..
I was keeping quite because no one was raising the issue.
Now that it has been raised i wish to have it to..
I successfully build the app but i was unable to change splashscreen and app name, after generating apk  the name debug appears after app name..

Please consider admob weather you can do it at a price or generally or documentation...

Bytheway i joined github because of your work.. thank you awinoawino938@gmail.com

**Comment by rhenwinch** [comment]
@Monicamonicah @Tvmax46 as much as I want to help, I'm in no way interested in providing extra time to add admob support/docs for this project. Since its an open source project, you could always play around with it and find a way how to do these things. 

Apologies; closing and locking this issue now. renaming it also for future similar issues.
