### ISSUE TITLE
Crash when playing a video

### ISSUE THREAD

**Issue by ToolDroidYT** [rhenwinch/Flixclusive#54]
### Steps to reproduce

Clicked a video to play

### Expected behavior

Open the video player

### Actual behavior

Crashed

### Crash logs (or stack trace)

java.lang.SecurityException: com.flixclusive: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
	at ya.k.a(SourceFile:34)
	at ya.k.invoke(SourceFile:267)
	at o0.k0.b(SourceFile:1)
	at o0.w.b(SourceFile:107)
	at o0.x.i(SourceFile:62)
	at o0.x.h(SourceFile:1)
	at o0.e2.invoke(SourceFile:168)
	at androidx.compose.ui.platform.e1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.c1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1045)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: xl.g: [o0.n1@fa663, androidx.compose.ui.platform.f2@eee3260, y1{Cancelling}@504e319, d1@e9c7fde]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16580)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
	at android.os.Binder.execTransactInternal(Binder.java:1375)

### Flixclusive version

1.4.0-beta

### Android version

Android 14 

### Device

Galaxy A14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by ToolDroidYT** [comment]
[https://stackoverflow.com/a/77276774/19030040](https://stackoverflow.com/a/77276774/19030040)

**Comment by rhenwinch** [comment]
Android 14+ bug. Sorry, will fix it on future updates
