### ISSUE TITLE
New beta doesn't work 

### ISSUE THREAD

**Issue by Parasgaming122** [rhenwinch/Flixclusive#55]
### Steps to reproduce

Policy accept button is getting cut and and can't click understand 😭

### Expected behavior

Work

### Actual behavior

Policy thingy getting cut and can't start app

### Flixclusive version

1.4.0

### Android version

Android 13

### Device

Smart tv box

### Other details

It worked before I updated and now doesn't 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
☠️ Sorry about this. Is this a screen size issue? Could you share a screenshot of the app pls

**Comment by Doctor2023** [comment]
java.lang.SecurityException: com.flixclusive: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6143)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
	at ya.k.a(SourceFile:34)
	at ya.k.invoke(SourceFile:267)
	at o0.k0.b(SourceFile:1)
	at o0.w.b(SourceFile:107)
	at o0.x.i(SourceFile:62)
	at o0.x.h(SourceFile:1)
	at o0.e2.invoke(SourceFile:168)
	at androidx.compose.ui.platform.e1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.c1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1069)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: xl.g: [o0.n1@1591e3b, androidx.compose.ui.platform.f2@6ca0958, y1{Cancelling}@4eefab1, d1@8db96]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16597)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11555)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2936)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3198)
	at android.os.Binder.execTransactInternal(Binder.java:1375)

this is what in the flixclusive app

**Comment by rhenwinch** [comment]
@Doctor2023 Wrong issue for wrong thread.


Check #53

**Comment by Doctor2023** [comment]
> @Doctor2023 Wrong issue for wrong thread.
> 
> Check #54

ok friend thanks you

**Comment by Parasgaming122** [comment]
![17086749273517588662770271618283](https://github.com/rhenwinch/Flixclusive/assets/98590880/2fab9d1b-b2f6-4c93-a294-9a9af216a6c9)
 Understood button doesn't work I tried using mouse and normal buttons

**Comment by Doctor2023** [comment]
![2024_02_25_17 01 04](https://github.com/rhenwinch/Flixclusive/assets/129991276/f7126bea-e36c-4fb7-a417-aa6e7c1f2931)


I get this when trying to play a movie and series with the sources, the video does not appear

**Comment by rhenwinch** [comment]
> Cannot find source
> 
> I get this when trying to play a movie and series with the sources, the video does not appear

Download the _latest release_ on the **prerelease** tag

**Comment by Parasgaming122** [comment]
> > Cannot find source
> > I get this when trying to play a movie and series with the sources, the video does not appear
> 
> Download the _latest release_ on the **prerelease** tag

Same error for me and I am using latest pre release

**Comment by Parasgaming122** [comment]
I found fix to the thing with understand thingy. When you click the down and ok button simultaneously you can click the understand button
