### ISSUE TITLE
App crashes on start. 

### ISSUE THREAD

**Issue by safdar9633** [rhenwinch/Flixclusive#82]
### Describe your suggested feature

Updates to the pre release version. The app crashes on start up

### Other details

com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "1h 33m"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:251)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:1014)
	at com.flixclusive.core.database.util.FilmDataConverter.toFilmData(FilmDataConverter.kt:22)
	at com.flixclusive.core.database.dao.WatchHistoryDao_Impl$5.call(WatchHistoryDao_Impl.java:196)
	at com.flixclusive.core.database.dao.WatchHistoryDao_Impl$5.call(WatchHistoryDao_Impl.java:153)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:129)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
	at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@5a09d86, androidx.compose.ui.platform.MotionDurationScaleImpl@1061647, StandaloneCoroutine{Cancelling}@c4b4e74, AndroidUiDispatcher@fafef9d]
Caused by: java.lang.NumberFormatException: For input string: "1h 33m"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:660)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1215)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
	... 20 more

**Comment by rhenwinch** [comment]
Will fix it urgently this day. I haven't tested the app. The current commits are unstable as hell I just had to push it for the providers system to keep up.

**Comment by rhenwinch** [comment]
Update the app manually thru github. Sorry for the inconvenience 🙏
