### ISSUE TITLE
GenreScreen crashes

### ISSUE THREAD

**Issue by rhenwinch** [rhenwinch/Flixclusive#83]
### Steps to reproduce

1. Open FilmScreen
2. Click "TV Show" or "Movie" genre pill

### Expected behavior

Should navigate seamlessly

### Actual behavior

Error occurs inside ViewModel, it seems.

### Crash logs (or stack trace)

java.lang.NullPointerException
	at com.flixclusive.feature.mobile.genre.GenreViewModel.<init>(GenreViewModel.kt:48)
	at com.flixclusive.DaggerFlixclusiveApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerFlixclusiveApplication_HiltComponents_SingletonC.java:850)
	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:102)
	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:90)
	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:114)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
	at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
	at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
	at com.flixclusive.feature.mobile.genre.GenreScreenKt.GenreScreen(GenreScreen.kt:72)
	at com.flixclusive.feature.mobile.genre.destinations.GenreScreenDestination.Content(GenreScreenDestination.kt:58)
	at com.ramcosta.composedestinations.dynamic.DynamicDestinationSpecKt$routedIn$1.Content(Unknown Source:32)
	at com.ramcosta.composedestinations.spec.DestinationStyleKt.CallComposable(DestinationStyle.kt:274)
	at com.ramcosta.composedestinations.spec.DestinationStyleKt.access$CallComposable(DestinationStyle.kt:1)
	at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$1.invoke(DestinationStyle.kt:163)
	at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$1.invoke(DestinationStyle.kt:162)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:320)
	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:318)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:318)
	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:302)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:755)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:744)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:818)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:726)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:709)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:768)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:280)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:129)
	at com.ramcosta.composedestinations.DefaultNavHostEngine.NavHost(DefaultNavHostEngine.kt:79)
	at com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost(DestinationsNavHost.kt:71)
	at com.flixclusive.util.NavigationHelperKt.AppNavHost(NavigationHelper.kt:105)
	at com.flixclusive.mobile.MobileAppKt$MobileApp$6.invoke(MobileApp.kt:193)
	at com.flixclusive.mobile.MobileAppKt$MobileApp$6.invoke(MobileApp.kt:189)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@92aa59e, androidx.compose.ui.platform.MotionDurationScaleImpl@bd2d87f, StandaloneCoroutine{Cancelling}@7f7104c, AndroidUiDispatcher@1f14895]

### Flixclusive version

pre-release

### Android version

10

### Device

Emulator

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by injusticedevil** [comment]
For me too
